# always active config
spring:
  application:
    name: Adv Java Final Project 
  redis:
    port: 6379
  profiles:
    active: "dev"



---
# Profile specific configs for dev profile

spring:
  profiles: dev
  #just for demo
  redis:
    host: 127.1.2.3
#    port: 6379
    password: meh
    
server:
  port: 8080
  servlet:
    session:
      timeout: 6h


---
# Profile specific configs for prod profile

spring:
  profiles: prod
  redis:
    host: 10.2.3.4
#    port: 6379  #defined at top 
    password: strngMeh
server:
  port: 80
  servlet:
    session:
      timeout: 30m